# Generated by Django 3.2.21 on 2023-10-28 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20231028_0652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agegroup',
            name='restriction_desc',
        ),
        migrations.RemoveField(
            model_name='agegroup',
            name='restriction_image',
        ),
        migrations.RemoveField(
            model_name='agegroup',
            name='restriction_name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='cat_desc',
        ),
        migrations.RemoveField(
            model_name='category',
            name='cat_image',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='condition_desc',
        ),
    ]
