# Generated by Django 3.2.21 on 2023-10-31 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_category_cat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='age',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.agegroup'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_players',
            field=models.CharField(default=1, max_length=1),
        ),
    ]
